name: Get Project Metadata

on:
  workflow_dispatch:

jobs:
  get-project-data:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      project: read

    steps:
      - name: Dump project and field info
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const query = `
              query {
                organization(login: "CSE-Alpha-2022-26") {
                  projectsV2(first: 10) {
                    nodes {
                      title
                      id
                      fields(first: 20) {
                        nodes {
                          __typename
                          ... on ProjectV2SingleSelectField {
                            id
                            name
                            options {
                              id
                              name
                            }
                          }
                          ... on ProjectV2Field {
                            id
                            name
                          }
                        }
                      }
                    }
                  }
                }
              }
            `;
            const result = await github.graphql(query);
            console.log("🧠 Project Metadata:\n", JSON.stringify(result, null, 2));
