name: Add New Mini Project Entry
description: Add your mini project details to the RSET CSE Project Tracker
title: "[Mini-Project] TeamX_ProjectName_2025"
labels: ["mini-project"]
body:
  - type: input
    id: title
    attributes:
      label: Project Title
      placeholder: Example: Smart OPD System
    validations:
      required: true

  - type: input
    id: repo
    attributes:
      label: Repository Link
      placeholder: https://github.com/CSE-Alpha-2022-26/TeamX_SmartOPD_2025
    validations:
      required: true

  - type: dropdown
    id: status
    attributes:
      label: Status
      options:
        - In Progress
        - Done
        - Reviewed
    validations:
      required: true

  - type: input
    id: assignees
    attributes:
      label: Assignees (GitHub usernames, comma-separated)
      placeholder: user1, user2
    validations:
      required: true

  - type: input
    id: phase
    attributes:
      label: Submission Phase
      placeholder: Phase 1 / Phase 2
    validations:
      required: true

  - type: input
    id: tags
    attributes:
      label: Tags (optional)
      placeholder: AI, Web, HealthTech
