name: Update Project Board Status

on:
  pull_request:
    types: [opened, closed]

jobs:
  update-status:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
      project: write

    steps:
      - name: Get PR details
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            const prTitle = pr.title;
            const isMerged = pr.merged;
            const status = isMerged ? "Done" : "In Progress";

            console.log(`Updating project field: Status = ${status}`);

            // NOTE: Replace these with your actual values
            const projectNumber = 1; // e.g., Project board #1
            const org = "CSE-Alpha-2022-26"; // your org/user

            // Find the project
            const projects = await github.rest.projects.listForOrg({
              org,
              state: "open"
            });

            const project = projects.data.find(p => p.name.includes("RSET CSE Mini-Project Tracker"));
            if (!project) {
              throw new Error("❌ Project not found!");
            }

            // Find the column based on PR state
            const columns = await github.rest.projects.listColumns({
              project_id: project.id
            });

            const column = columns.data.find(c => c.name === status);
            if (!column) {
              throw new Error(`❌ Column '${status}' not found`);
            }

            // Add card to correct column
            await github.rest.projects.createCard({
              column_id: column.id,
              content_id: pr.id,
              content_type: "PullRequest"
            });
